build:
    nodes:
        analysis:
            tests:
              override:
                - php-scrutinizer-run
        coverage:
            tests:
                override:
                    - command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                      coverage:
                        file: clover.xml
                        format: clover
        my-node:
            services:
                redis: 4
    environment:
        variables:
            DB_HOSTNAME: '127.0.0.1'
            DB_DATABASE: 'rest_api_slim_php'
            DB_USERNAME: 'root'
            DB_PASSWORD: ''
            DISPLAY_ERROR_DETAILS: true
            APP_DOMAIN: 'https://rest-api-slim-php-sql.herokuapp.com'
            SECRET_KEY: 'YourSuperSecret-KeY'
            REDIS_ENABLED: true
            REDIS_URL: 'localhost'
            LOGS_ENABLED: true
        php:
            version: 7.4
    project_setup:
        before:
            - mysql -e "CREATE DATABASE rest_api_slim_php"
            - mysql rest_api_slim_php < database/database.sql
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
