--
-- Script para importar datos de prueba
-- github.com/fernandocalmet
--
INSERT INTO `modulos` (`nombre`) VALUES ('Operaciones');
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Crear operacion', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Eliminar operacion', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Detalles de operacion', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Modificar operacion', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Listar operaciones', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Crear rol', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Eliminar rol', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Detalles de rol', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Modificar rol', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Listar roles', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Crear permiso', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Eliminar permiso', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Detalles de permiso', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Modificar permiso', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Listar permisos', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Crear usuario', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Eliminar usuario', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Detalles de usuario', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Modificar usuario', 1);
INSERT INTO `operaciones` (`nombre`, `id_modulo`) VALUES ('Listar usuarios', 1);
INSERT INTO `roles` (`nombre`) VALUES ('Developer');
INSERT INTO `roles` (`nombre`) VALUES ('Administrador');
INSERT INTO `roles` (`nombre`) VALUES ('Supervisor');
INSERT INTO `roles` (`nombre`) VALUES ('Cliente');
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 1);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 2);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 3);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 4);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 5);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 6);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 7);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 8);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 9);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 10);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 11);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 12);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 13);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 14);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 15);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 16);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 17);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 18);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 19);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 20);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 21);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 22);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 23);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 24);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (1, 25);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 3);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 5);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 8);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 10);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 13);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 15);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 18);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 20);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 21);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 22);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 23);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 24);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (2, 25);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 3);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 5);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 8);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 10);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 13);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 15);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 18);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 20);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 23);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (3, 25);
INSERT INTO `permisos` (`id_rol`, `id_operacion`) VALUES (4, 25);
INSERT INTO `usuarios` (`correo`, `clave`, `nombre`, `id_rol`) VALUES ('fercalmet@gmail.com', '12345678', 'Fernando Calmet', 1);